# version of docker compose
version: '3.7'

services:
    
    fastapi:
         image: lfss08/stfastapi:trading
         ports:
           - 80:8000
         volumes:
             - ./app:/app
         environment:
           - API_KEY=${API_KEY}
           - DATABASE_USERNAME = ${DATABASE_USERNAME}
           - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
           - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
           - DATABASE_PORT = ${DATABASE_PORT}
           - DATABASE_NAME = ${DATABASE_NAME}
         
         depends_on:
           - postgres
         
    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
          - POSTGRES_DB= ${DATABASE_NAME}

      volumes:
          - postgres-db:/var/lib/postgresql/data
          
volumes:
   postgres-db: